default:
  before_script:
  - echo "${PATH}"
  - date
  - pwd
  - unset cd
  - eval "$(rbenv init -)"
  - bundle install
  - xcversion install "13.2.1"

stages:
  - test

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

swift lint:
  timeout: 5 minutes
  dependencies: []
  stage: test
  artifacts:
    when: always
    paths:
      - fastlane/codequality_report.json
    reports:
      codequality: fastlane/codequality_report.json
  script:
    - bundle exec fastlane lint
  rules:
    - if: '$SWIFT_LINT_DISABLED'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: '$CI_COMMIT_TAG'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_BRANCH == "develop"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  tags:
    - macos

test_project:
  stage: test
  artifacts:
    expire_in: 7d
    when: always
    paths:
      - fastlane/test_output/tests.xml
      - logs
    reports:
      coverage_report:
        coverage_format: cobertura
        path: cobertura.xml    
      junit: test_output/tests.xml
  coverage: '/Test Coverage\: \d+(?:\.\d*)?\%/'
  only:
    - merge_requests
    - master
    - develop
  script:
    - bundle exec fastlane tests
  tags:
  - macos
