stages:
  - test

swift lint:
  timeout: 5 minutes
  dependencies: []
  stage: test
  artifacts:
    when: always
    paths:
      - codequality_report.json
    reports:
      codequality: codequality_report.json
  script:
    - bundle exec fastlane lint
  rules:
    - if: '$SWIFT_LINT_DISABLED'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: '$CI_COMMIT_TAG'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_BRANCH == "develop"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  tags:
    - macos

test_project:
  stage: test
  artifacts:
    expire_in: 7d
    when: always
    paths:
      - cobertura.xml
      - test_output/tests.xml
      - logs
    reports:
      cobertura: cobertura.xml
      junit: test_output/tests.xml
  script:
    - xcodebuild clean -project AutoUpdate.xcodeproj -scheme AutoUpdate | xcpretty
    - xcodebuild test -project AutoUpdate.xcodeproj -scheme AutoUpdate | xcpretty -s
  tags:
  - macos